name: raro_academy_budget
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  animated_card: ^2.0.0
  connectivity: ^3.0.6
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0
  cpf_cnpj_validator: ^2.0.0
  intl: ^0.17.0
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf